// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq8Cbg7RwRb9KERwu6MgBl9rrQi4UMVHs',
    appId: '1:1032670758538:web:d88edc30fdee4b7909cf73',
    messagingSenderId: '1032670758538',
    projectId: 'chicsphere-85061',
    authDomain: 'chicsphere-85061.firebaseapp.com',
    storageBucket: 'chicsphere-85061.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIEbx7Qp_Wlq4eD6v-0bW_1WwxwbI0L58',
    appId: '1:1032670758538:android:805d6d15f394331109cf73',
    messagingSenderId: '1032670758538',
    projectId: 'chicsphere-85061',
    storageBucket: 'chicsphere-85061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyRWB31LC05Zl7aCRwD3XwgJ53uU8OEQ',
    appId: '1:1032670758538:ios:f65d31cb504a5eb709cf73',
    messagingSenderId: '1032670758538',
    projectId: 'chicsphere-85061',
    storageBucket: 'chicsphere-85061.firebasestorage.app',
    iosBundleId: 'com.example.chicSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyRWB31LC05Zl7aCRwD3XwgJ53uU8OEQ',
    appId: '1:1032670758538:ios:f65d31cb504a5eb709cf73',
    messagingSenderId: '1032670758538',
    projectId: 'chicsphere-85061',
    storageBucket: 'chicsphere-85061.firebasestorage.app',
    iosBundleId: 'com.example.chicSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq8Cbg7RwRb9KERwu6MgBl9rrQi4UMVHs',
    appId: '1:1032670758538:web:97a2128e716a84f409cf73',
    messagingSenderId: '1032670758538',
    projectId: 'chicsphere-85061',
    authDomain: 'chicsphere-85061.firebaseapp.com',
    storageBucket: 'chicsphere-85061.firebasestorage.app',
  );
}
